name: Creating new version
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Input next version'
        required: true
        default: '0.0.0'
      new-release-version:
        description: 'Criar branch de RC?'
        required: true
        default: 'false'
jobs:
  release-candidate:
    name: Create branch RC
    environment:
      name: zappts
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.new-release-version == 'true' }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<steff.vasem@gmail.com"
        git checkout main
        git checkout -b rc/"${{ github.event.inputs.tag }}"
        git push --set-upstream origin rc/"${{ github.event.inputs.tag }}"
  tag:
    name:  Create a tag
    environment:
      name: zappts
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<steff.vasem@gmail.com"
        git checkout rc/"${{ github.event.inputs.tag }}"
        git tag v"${{ github.event.inputs.tag }}"
        git push --set-upstream origin v"${{ github.event.inputs.tag }}"
        git push origin --delete rc/"${{ github.event.inputs.tag }}"
  release:
    name: Create Release
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: v${{ github.event.inputs.tag }}
          release_name: v${{ github.event.inputs.tag }}
          body: |
            Changes in this Release
            - Elaborar melhor notas da release
          draft: false
          prerelease: false